### PR TITLE
 Renamed chat to AI Tutor

### PR DESCRIPTION
**Pull request by vinayakhegde1**
This PR fixes [#470]
Renamed chat to AI Tutor

### CODE REVIEW

**Review by iomodo — CHANGES_REQUESTED** [review]
Hey @vinayakhegde1, thanks a lot for the contribution! It looks great!
Let's Route actual component to `/dashboard/ai-tutor` as well
  
You can see the code here:
https://github.com/oseducation/knowledge-graph/blob/be8589a25df1f0fbac3ff018bb6c15a0f52eb98b/webapp/src/App.tsx#L46

**Comment by vinayakhegde1** [comment]
@iomodo Sorry for the inconvenience but currently I'm away from my main system

**Comment by iomodo** [comment]
No worries @vinayakhegde1 take your time.
I'll update myself later if you won't be able to finish by release time

**Comment by iomodo** [comment]
Closing in favor of https://github.com/oseducation/knowledge-graph/pull/503
Your commits are there @vinayakhegde1, thanks a lot for the contribution <3

**Comment by vinayakhegde1** [comment]
@iomodo Welcome

**Pull request closed without merging**
